# Generated by Django 5.2.7 on 2026-05-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="knowledgeextractionhistory",
            new_name="ai_service__user_id_685b62_idx",
            old_name="ai_service__user_id_313cb6_idx",
        ),
    ]
