# Generated by Django 5.2.7 on 2025-10-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_avatar_userprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_deep_thinking',
            field=models.BooleanField(default=True, verbose_name='启用深度思考模式'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_ai_model',
            field=models.CharField(default='deepseek', max_length=50, verbose_name='偏好AI模型'),
        ),
    ]
