# Generated by Django 5.2.7 on 2026-05-24 12:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ocr", "0001_add_sha256_hash_to_files"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.CreateModel(
            name="CommissionBasic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_number", models.CharField(max_length=50)),
                ("commission_number", models.CharField(max_length=50, unique=True)),
                (
                    "service_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("need_report", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "commission_department",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "commissioner",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("commission_date", models.DateField(blank=True, null=True)),
                (
                    "commission_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "sample_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sample_quantity",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sample_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sample_batch",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "product_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sample_weight",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("delivery_time", models.DateTimeField(blank=True, null=True)),
                ("required_time", models.DateField(blank=True, null=True)),
                (
                    "sample_disposal",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "storage_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "project_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "material_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("test_nature", models.CharField(blank=True, max_length=50, null=True)),
                ("test_description", models.TextField(blank=True, null=True)),
                (
                    "special_condition_flag",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "special_condition_detail",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "product_quantity",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tester", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "data_reviewer",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("review_date", models.DateField(blank=True, null=True)),
                (
                    "form_complete",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "sample_info_consistent",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "sample_condition_ok",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "other_notes",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "delivery_person_signature",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_receiver_signature",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "commission_basic",
            },
        ),
    migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("stored_filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField()),
                ("file_type", models.CharField(max_length=50)),
                (
                    "document_type_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("md5_hash", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "sha256_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "upload_batch_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("ocr_status", models.CharField(default="pending", max_length=20)),
                ("ocr_started_at", models.DateTimeField(blank=True, null=True)),
                ("ocr_completed_at", models.DateTimeField(blank=True, null=True)),
                ("ocr_error_message", models.TextField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(default="unassigned", max_length=20),
                ),
                ("review_started_at", models.DateTimeField(blank=True, null=True)),
                ("review_completed_at", models.DateTimeField(blank=True, null=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("tags", models.CharField(blank=True, max_length=500, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "files",
            },
        ),
    migrations.CreateModel(
            name="ModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("api_url", models.CharField(max_length=500)),
                ("file_type", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("config_params", models.JSONField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("timeout", models.IntegerField(default=120)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "model_configs",
            },
        ),
    migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("real_name", models.CharField(blank=True, max_length=50, null=True)),
                ("role", models.CharField(default="user", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("avatar_url", models.CharField(blank=True, max_length=255, null=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
    migrations.CreateModel(
            name="CommissionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_filename", models.CharField(max_length=255)),
                ("minio_object_name", models.CharField(max_length=500)),
                ("minio_bucket", models.CharField(max_length=100)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("file_md5", models.CharField(blank=True, max_length=32, null=True)),
                ("page_count", models.IntegerField(default=1)),
                ("extraction_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "commission_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "commission_documents",
                "indexes": [
                    models.Index(fields=["pdf_filename"], name="idx_pdf_filename"),
                    models.Index(
                        fields=["commission_number"], name="idx_commission_number"
                    ),
                    models.Index(fields=["created_at"], name="idx_created_at"),
                ],
            },
        ),
    migrations.CreateModel(
            name="FileTypeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_code", models.CharField(max_length=50, unique=True)),
                ("type_name", models.CharField(max_length=100)),
                ("type_description", models.TextField(blank=True, null=True)),
                ("ocr_config", models.JSONField(blank=True, null=True)),
                ("storage_tables", models.JSONField(default=list)),
                ("adapter_class", models.CharField(max_length=100)),
                (
                    "adapter_module",
                    models.CharField(default="adapters", max_length=200),
                ),
                ("form_config", models.JSONField(blank=True, null=True)),
                (
                    "form_component",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("validation_rules", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_config",
                    models.ForeignKey(
                        blank=True,
                        db_column="model_config_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_types",
                        to="ocr.modelconfig",
                    ),
                ),
            ],
            options={
                "db_table": "file_type_configs",
            },
        ),
    migrations.CreateModel(
            name="OCRResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.IntegerField()),
                ("raw_text", models.TextField(blank=True, null=True)),
                ("raw_result", models.JSONField(blank=True, null=True)),
                ("table_data", models.JSONField(blank=True, null=True)),
                ("form_fields", models.JSONField(blank=True, null=True)),
                ("text_regions", models.JSONField(blank=True, null=True)),
                ("table_regions", models.JSONField(blank=True, null=True)),
                ("handwriting_regions", models.JSONField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("ocr_engine", models.CharField(default="PaddleOCR", max_length=50)),
                ("ocr_version", models.CharField(blank=True, max_length=20, null=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                ("review_status", models.CharField(default="pending", max_length=20)),
                ("corrected_table_data", models.JSONField(blank=True, null=True)),
                ("corrected_form_fields", models.JSONField(blank=True, null=True)),
                ("correction_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file",
                    models.ForeignKey(
                        db_column="file_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_results",
                        to="ocr.file",
                    ),
                ),
            ],
            options={
                "db_table": "ocr_results",
            },
        ),
    migrations.CreateModel(
            name="SpecialTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_type", models.CharField(max_length=20)),
                ("element_name", models.CharField(max_length=50)),
                (
                    "standard_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "measured_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("remark", models.CharField(blank=True, max_length=200, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "commission",
                    models.ForeignKey(
                        db_column="commission_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_tests",
                        to="ocr.commissionbasic",
                        to_field="commission_number",
                    ),
                ),
            ],
            options={
                "db_table": "special_tests",
            },
        ),
    migrations.CreateModel(
            name="TestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_item", models.CharField(max_length=100)),
                (
                    "test_equipment",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "test_standard",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "test_condition",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_standard",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                ("test_result", models.TextField(blank=True, null=True)),
                ("tester", models.CharField(blank=True, max_length=30, null=True)),
                ("remark", models.CharField(blank=True, max_length=200, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "commission",
                    models.ForeignKey(
                        db_column="commission_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_items",
                        to="ocr.commissionbasic",
                        to_field="commission_number",
                    ),
                ),
            ],
            options={
                "db_table": "test_items",
            },
        ),
        migrations.CreateModel(
            name="ReviewRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_type", models.CharField(max_length=20)),
                ("action_type", models.CharField(max_length=20)),
                ("field_name", models.CharField(blank=True, max_length=100, null=True)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("row_index", models.IntegerField(blank=True, null=True)),
                ("column_index", models.IntegerField(blank=True, null=True)),
                ("coordinates", models.JSONField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, null=True)),
                (
                    "confidence_level",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("is_confirmed", models.BooleanField(default=True)),
                ("error_type", models.CharField(blank=True, max_length=50, null=True)),
                ("severity", models.CharField(blank=True, max_length=10, null=True)),
                ("review_duration", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "file",
                    models.ForeignKey(
                        db_column="file_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_records",
                        to="ocr.file",
                    ),
                ),
                (
                    "ocr_result",
                    models.ForeignKey(
                        blank=True,
                        db_column="ocr_result_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_records",
                        to="ocr.ocrresult",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        db_column="reviewer_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_records",
                        to="ocr.user",
                    ),
                ),
            ],
            options={
                "db_table": "review_records",
            },
        ),
    migrations.AddField(
            model_name="modelconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ocr.user",
            ),
        ),
    migrations.CreateModel(
            name="FileAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_type", models.CharField(default="review", max_length=20)),
                ("priority", models.CharField(default="medium", max_length=10)),
                ("status", models.CharField(default="assigned", max_length=20)),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_duration", models.IntegerField(blank=True, null=True)),
                ("actual_duration", models.IntegerField(blank=True, null=True)),
                ("assignment_notes", models.TextField(blank=True, null=True)),
                ("completion_notes", models.TextField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("quality_score", models.IntegerField(blank=True, null=True)),
                ("is_approved", models.BooleanField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("reassignment_count", models.IntegerField(default=0)),
                (
                    "file",
                    models.ForeignKey(
                        db_column="file_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="ocr.file",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="approved_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_assignments",
                        to="ocr.user",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        db_column="assigned_by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_assignments",
                        to="ocr.user",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        db_column="assigned_to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_files",
                        to="ocr.user",
                    ),
                ),
                (
                    "previous_assignee",
                    models.ForeignKey(
                        blank=True,
                        db_column="previous_assignee",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_assignments",
                        to="ocr.user",
                    ),
                ),
            ],
            options={
                "db_table": "file_assignments",
            },
        ),
    migrations.AddField(
            model_name="file",
            name="uploader",
            field=models.ForeignKey(
                db_column="uploader_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_files",
                to="ocr.user",
            ),
        ),
    migrations.CreateModel(
            name="CommissionOcrResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_pdf_path", models.CharField(max_length=500)),
                ("ocr_raw_data", models.TextField(blank=True, null=True)),
                ("field_mapping", models.TextField(blank=True, null=True)),
                ("total_fields", models.IntegerField(default=0)),
                ("recognized_fields", models.IntegerField(default=0)),
                (
                    "avg_confidence",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("ocr_status", models.CharField(default="pending", max_length=20)),
                ("review_status", models.CharField(default="pending", max_length=20)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commission",
                    models.ForeignKey(
                        db_column="commission_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_results",
                        to="ocr.commissionbasic",
                        to_field="commission_number",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        db_column="reviewer_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_reviewed_results",
                        to="ocr.user",
                    ),
                ),
            ],
            options={
                "db_table": "commission_ocr_results",
            },
        ),
    migrations.CreateModel(
            name="CommissionExtractedField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.IntegerField()),
                ("field_name", models.CharField(max_length=100)),
                ("field_value", models.TextField(blank=True, null=True)),
                ("field_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "extraction_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "source_block_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("source_block_text", models.TextField(blank=True, null=True)),
                ("bbox_json", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "document",
                    models.ForeignKey(
                        db_column="document_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_fields",
                        to="ocr.commissiondocument",
                    ),
                ),
            ],
            options={
                "db_table": "commission_extracted_fields",
                "indexes": [
                    models.Index(fields=["document"], name="idx_document_id"),
                    models.Index(fields=["field_name"], name="idx_field_name"),
                    models.Index(fields=["page_number"], name="idx_page_number"),
                ],
            },
        ),
    migrations.CreateModel(
            name="CommissionStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.IntegerField()),
                ("source_content_blocks", models.IntegerField(blank=True, null=True)),
                ("grid_cells_count", models.IntegerField(blank=True, null=True)),
                ("matched_cells_count", models.IntegerField(blank=True, null=True)),
                ("total_fields_extracted", models.IntegerField(blank=True, null=True)),
                ("single_cell_fields", models.IntegerField(blank=True, null=True)),
                ("adjacent_cell_fields", models.IntegerField(blank=True, null=True)),
                ("handwritten_fields", models.IntegerField(blank=True, null=True)),
                ("table_data_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "document",
                    models.ForeignKey(
                        db_column="document_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="ocr.commissiondocument",
                    ),
                ),
            ],
            options={
                "db_table": "commission_statistics",
                "indexes": [
                    models.Index(fields=["document"], name="idx_document_id_stats")
                ],
            },
        ),
            ],
            database_operations=[],
        ),
    ]
