# Generated by Django 5.2.7 on 2026-06-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0004_create_missing_ocr_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="batch_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="minio_bucket",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="minio_object_key",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
