# Generated by Django 5.2.7 on 2026-06-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0005_file_batch_id_file_minio_bucket_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_name", models.CharField(max_length=50, unique=True)),
                ("document_type_code", models.CharField(max_length=20)),
                ("file_count", models.IntegerField(default=0)),
                ("max_count", models.IntegerField(default=2000)),
                ("status", models.CharField(default="open", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remark", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
