# Generated by Django 5.2.7 on 2025-11-01 10:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="任务标题")),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                ("input_data", models.JSONField(verbose_name="输入数据")),
                (
                    "output_data",
                    models.JSONField(blank=True, null=True, verbose_name="输出数据"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "progress",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="进度百分比",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "execution_time",
                    models.FloatField(blank=True, null=True, verbose_name="执行时间(秒)"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                ("error_traceback", models.TextField(blank=True, verbose_name="错误堆栈")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "智能体任务",
                "verbose_name_plural": "智能体任务",
                "db_table": "agent_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_name", models.CharField(max_length=100, verbose_name="步骤名称")),
                ("step_order", models.PositiveIntegerField(verbose_name="步骤顺序")),
                ("input_data", models.JSONField(verbose_name="步骤输入")),
                (
                    "output_data",
                    models.JSONField(blank=True, null=True, verbose_name="步骤输出"),
                ),
                ("started_at", models.DateTimeField(verbose_name="开始时间")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("logs", models.TextField(blank=True, verbose_name="执行日志")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="smart_agent.agenttask",
                    ),
                ),
            ],
            options={
                "verbose_name": "执行记录",
                "verbose_name_plural": "执行记录",
                "db_table": "agent_execution",
                "ordering": ["step_order"],
            },
        ),
        migrations.CreateModel(
            name="SmartAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="智能体名称")),
                ("display_name", models.CharField(max_length=200, verbose_name="显示名称")),
                ("description", models.TextField(verbose_name="描述")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("data_analysis", "数据分析"),
                            ("property_prediction", "性质预测"),
                            ("process_optimization", "工艺优化"),
                            ("knowledge_extraction", "知识抽取"),
                            ("decision_support", "决策支持"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="分类",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=100, verbose_name="图标类名"),
                ),
                (
                    "color_theme",
                    models.CharField(default="blue", max_length=20, verbose_name="主题色"),
                ),
                ("avatar_url", models.URLField(blank=True, verbose_name="头像URL")),
                ("capabilities", models.JSONField(default=list, verbose_name="能力列表")),
                (
                    "supported_inputs",
                    models.JSONField(default=list, verbose_name="支持的输入类型"),
                ),
                (
                    "supported_outputs",
                    models.JSONField(default=list, verbose_name="支持的输出类型"),
                ),
                (
                    "ai_model",
                    models.CharField(
                        help_text="如: gpt-4, claude-3等",
                        max_length=100,
                        verbose_name="AI模型",
                    ),
                ),
                ("model_config", models.JSONField(default=dict, verbose_name="模型配置")),
                ("prompt_template", models.TextField(verbose_name="提示词模板")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("inactive", "非活跃"),
                            ("maintenance", "维护中"),
                            ("deprecated", "已弃用"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="是否公开")),
                (
                    "popularity_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                        verbose_name="受欢迎程度",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="使用次数"),
                ),
                (
                    "success_rate",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="成功率",
                    ),
                ),
                (
                    "average_execution_time",
                    models.FloatField(default=0.0, verbose_name="平均执行时间(秒)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "version",
                    models.CharField(default="1.0.0", max_length=20, verbose_name="版本"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_agents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "智能体",
                "verbose_name_plural": "智能体",
                "db_table": "smart_agent",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="agenttask",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="smart_agent.smartagent",
            ),
        ),
        migrations.CreateModel(
            name="AgentFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="评分(1-5)",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="评论")),
                ("tags", models.JSONField(default=list, verbose_name="标签")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="反馈者",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smart_agent.agenttask",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="smart_agent.smartagent",
                    ),
                ),
            ],
            options={
                "verbose_name": "智能体反馈",
                "verbose_name_plural": "智能体反馈",
                "db_table": "agent_feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
