# Generated by Django 5.2 on 2025-12-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_agent", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smartagent",
            name="category",
            field=models.CharField(
                choices=[
                    ("data_analysis", "数据分析"),
                    ("property_prediction", "性质预测"),
                    ("process_optimization", "工艺优化"),
                    ("formula_generation", "配方生成"),
                    ("knowledge_extraction", "知识抽取"),
                    ("decision_support", "决策支持"),
                    ("other", "其他"),
                ],
                default="other",
                max_length=50,
                verbose_name="分类",
            ),
        ),
    ]
