# Generated by Django 5.2.7 on 2025-10-15 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文档标题')),
                ('description', models.TextField(blank=True, verbose_name='文档描述')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='文件')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF文档'), ('doc', 'Word文档'), ('docx', 'Word文档'), ('txt', '文本文件'), ('md', 'Markdown文档'), ('ppt', 'PowerPoint'), ('pptx', 'PowerPoint'), ('xls', 'Excel表格'), ('xlsx', 'Excel表格'), ('image', '图片文件'), ('other', '其他文件')], max_length=10, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='标签（逗号分隔）')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '文档资料',
                'verbose_name_plural': '文档资料',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('action', models.CharField(choices=[('view', '查看'), ('download', '下载')], default='view', max_length=20, verbose_name='操作类型')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文档访问记录',
                'verbose_name_plural': '文档访问记录',
                'ordering': ['-access_time'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('color', models.CharField(default='#1890ff', max_length=7, verbose_name='分类颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '文献分类',
                'verbose_name_plural': '文献分类',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory', verbose_name='所属分类'),
        ),
    ]
