# Generated by Django 5.2.7 on 2025-10-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentfolder_document_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF文档'), ('doc', 'Word文档'), ('docx', 'Word文档'), ('txt', '文本文件'), ('md', 'Markdown文档'), ('csv', 'CSV文件'), ('ppt', 'PowerPoint'), ('pptx', 'PowerPoint'), ('xls', 'Excel表格'), ('xlsx', 'Excel表格'), ('image', '图片文件'), ('other', '其他文件')], max_length=10, verbose_name='文件类型'),
        ),
    ]
