# Generated by Django 5.2.6 on 2025-09-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='dify_message_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dify消息ID'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='dify_conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dify对话ID'),
        ),
    ]
