# Generated by Django 5.2.7 on 2025-10-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_dify_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='消息元数据'),
        ),
    ]
